### PR TITLE
Tournaments from position

### PR DESCRIPTION
**Pull request by TheYoBots**
Merged from upstream.

Fixes https://github.com/WandererXII/lishogi/issues/438

### CODE REVIEW

**Comment by WandererXII** [comment]
Ready to merge or still WIP?

**Comment by TheYoBots** [comment]
I'll have to run a few tests. After which I'll rebase this branch. Then you could merge it. Thanks!

**Comment by TheYoBots** [comment]
@WandererXII This Pr is ready. Do mention if I need to make any changes.

**Comment by WandererXII** [comment]
Very nice!

**Pull request merged**
