### PR TITLE
Fix challenge clock validation

### PR DESCRIPTION
**Pull request by TheYoBots**
Prevents users from creating 0+0|0 challenges.

Prevents creating the following challenges with API:
- Open ended challenges
- Challenging another user with the API
- Challenging the AI with the API

https://github.com/RoepStoep/lidraughts/commit/758f33ba1714aa0c5f92cf94d96b5923771750bb

### CODE REVIEW

**Comment by LishogiContributor** [comment]
create ore tourney at least maybe 5 tournaments at a time it. https://github.com/ornicar/lila/pull/9196#issue-671065881

**Comment by TheYoBots** [comment]
> create ore tourney at least maybe 5 tournaments at a time it. [ornicar#9196 (comment)](https://github.com/ornicar/lila/pull/9196#issue-671065881)

I think you mean to create an issue instead of commenting here.

**Comment by WandererXII** [comment]
We also need `c.hasByoyomi`

**Comment by WandererXII** [comment]
Thanks

**Comment by littlebasiccoder** [comment]
**@TheYoBots @WandererXII still it didn't fix https://lishogi.org/15gr8KXL**

**Pull request merged**
