### PR TITLE
Dropbug fix

### LINKED ISSUE #210: Clicking your own piece on board does not deselect hand piece.
(See also another hand piece issue #208, but this one is different)

It's my turn
Click piece in hand
Click piece on board -- hand piece not deselected, board piece is also selected
Click square on board -- it will drop from hand instead of moving the board piece

### PR DESCRIPTION
**Pull request by killerducky**
This is to fix #210, still needs work, thus the debug consoles etc still in there. Looking for early feedback if I'm going the right direction here.

drag.ts start function needs to call cancelDropMode. The start function seems to handle clicks on the main board that will start dragging a piece somewhere, so that should override any selected pieces.

crazyView.ts was looking ctrl.selected that crazyCtrl.ts was updating. It looks like that code is not needed at all, instead just look directly at ctrl.shogiground?.state.dropmode. 

Need to look more at the round and puzzle versions of crazyView. Quick look they seem to already use shogiground.state.

There is still a problem with redraw:
Click a hand piece
Click a board piece
Now the hand piece is canceled logically, but visually the selected-square class is still applied.
Hit "f" to flip the board and the redraw works correctly. 
I haven't figured out why it's not redrawing correctly.

### CODE REVIEW

**Comment by killerducky** [comment]
About the redraw problem:
drag.ts function start is responsible for calling cancelDropMode. This sets dropmode.active=false.
Then it calls s.dom.redraw()

But crazyView.ts default function does not rerun, based on console logs and debug points. Maybe it needs to have another addEventListener added?

**Comment by killerducky** [comment]
@WandererXII 
I cleaned up the debug logs and I think this is good enough to merge as-is now. There is still the issue with the display, but at least the main buggy behavior is fixed.

**Comment by WandererXII** [comment]
Looks really nice, thanks!

**Comment by WandererXII** [comment]
I will fix the display issue too, the problem is that the drop gets cancelled inside shogiground, it redraws itself, but the pocket is outside, not aware it should redraw.

**Pull request merged**
