### PR TITLE
Created set.

### PR DESCRIPTION
**Pull request by nexxogen**
Created a set of 1-kanji pieces in the Ryoko style.

### CODE REVIEW

**Comment by WandererXII** [comment]
Hey, these look really great. I really like them a lot. Thanks!

**Comment by nexxogen** [comment]
Will the pieces be available on lishogi to select soon?

**Comment by WandererXII** [comment]
I am currently working on the update. I will update the server together with some other new stuff. I think I could have it ready tomorrow or the day after, if everything goes well.

**Comment by nexxogen** [comment]
Awesome, thanks.

**Pull request merged**
