### PR TITLE
Joyful slightly remade

### PR DESCRIPTION
**Pull request by Rechefiltr-is-Fire**

### CODE REVIEW

**Comment by WandererXII** [comment]
Since sente and gote pieces are different, it's a bit more complicated. We have sente pieces facing up, sente pieces facing down, gote pieces facing up and gote pieces facing down. With some pieces you overwrote a piece facing down with a piece facing down.
image

I understand it's rather tedious to do with github file upload, so please just paste the pieces you want me to replace and I will do it. Thanks!

**Comment by Rechefiltr-is-Fire** [comment]
1GI
1GI-1
1NG
1NG-1
1TO
1TO-1
1GI
1GI-1
1NG
1NG-
<img width=
1TO-1
1" src="https://user-images.githubusercontent.com/101206332/231716562-654bd727-0438-43b1-acc7-6b75a416d0f5.png">

**Comment by WandererXII** [comment]
Oh, I see. The rotation information was shown in Exif metadata, but the image itself was actually not rotated, so it depended whether the exif metadata was being respected. I will update the pieces on the site today or tomorrow. Thanks.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/c7fd052a977bb452de53f7a7eb19404c81417c1a

**Pull request closed without merging**
