### PR TITLE
Document endpoint /api/player/autocomplete (fix #847)

### LINKED ISSUE #847: API - autocomplete user name
Suggestion: add feature https://lichess.org/api#tag/Users/operation/apiPlayerAutocomplete so Discord client (and someday a Lishogi mobile app) can autocomplete usernames.

### PR DESCRIPTION
**Pull request by ddugovic**
I am struggling to test this patch at the moment, however I think this should be close to correct.

### CODE REVIEW

**Comment by WandererXII** [comment]
`/player/autocomplete` is used in some places, so I think it would be better to keep that url.

**Comment by ddugovic** [comment]
OK... other lila-based sites use prefix `/api` for API endpoints, but Lishogi can be different for backward compatibility reasons.

**Comment by ddugovic** [comment]
Sorry... actually, could I update the "ui" references to this endpoint to use `/api/player/autocomplete` ?  Long-term it may help both future lishogi development (copying code from lila) and help client API designers to expect the same endpoint on both Lichess and Lishogi.

I can't imagine there being many other consumers of this endpoint (like mobile applications) since for Lishogi this endpoint wasn't documented/announced yet.

**Comment by WandererXII** [comment]
LGTM, thanks!

**Pull request merged**
