### PR TITLE
Change Chess Transparent background to a Shogi One

### PR DESCRIPTION
**Pull request by TheYoBots**
Image taken from [here](https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F304415256047511776%2F&psig=AOvVaw3FaGP0H5k3CW6c1PnD0CCD&ust=1615201142344000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIjB76SDnu8CFQAAAAAdAAAAABAJ). No copyright terms as such. In case you would like something else close this PR. In case you would like to see how the background would look you could go [here](https://github.com/TheYoBots/lishogi/blob/transparent-background/public/images/background/landscape.jpg).

### CODE REVIEW

**Comment by justremember** [comment]
Image file doesn't match the original's size, even if rotated 90 degrees.

**Comment by TheYoBots** [comment]
Thanks for your review.

I’ve resized it, but it is still slightly different from the original lichess transparent background. I have even tested it and it looks much better now. Here’s how it looks...

https://imgur.com/TuHET7C

**Comment by justremember** [comment]
- It will probably look worse on 1920x1080 screens if stretched. The image is only 1500 wide. Not 100% sure as I don't have a 1080p screen.
- "No copyright terms" does not mean you are free to use the images however you want... https://www.quora.com/Can-I-use-images-from-Pinterest-on-my-website

**Comment by TheYoBots** [comment]
Ok, then I’ll close this PR cuz I don’t want lishogi to get into any issues on regards to the image and also because I’m unable to make it compatible on a 1920x1080 screen.

Thanks a lot for helping me out here :)

**Pull request closed without merging**
