### PR TITLE
Make it easier to get on the leaderboard - Solve #724

### PR DESCRIPTION
**Pull request by M-DinhHoangViet**
Change Glicko: 
Standard 75 -> 80
Variants: 65 -> 75
I think this PR can solve #724

### CODE REVIEW

**Comment by WandererXII** [comment]
Could you just increase chushogi to 85 and maybe other variants to 70, I think it's better to keep standard as is.

**Comment by M-DinhHoangViet** [comment]
Can I increase Annan Shogi to 80 or 75?

**Comment by M-DinhHoangViet** [comment]
@WandererXII If I made any mistake please correct it.

**Comment by WandererXII** [comment]
Looks great. Thanks!

**Pull request merged**
