### PR TITLE
Maybe Twitch changed the Shogi game ID

### PR DESCRIPTION
**Pull request by ddugovic**

### CODE REVIEW

**Comment by WandererXII** [comment]
Thanks, where did you find the id?

**Comment by ddugovic** [comment]
I searched https://dev.twitch.tv/docs/api/reference#get-games for name=Shogi .

**Comment by WandererXII** [comment]
Have you seen any twitch streams pop up on lishogi lately? Is it therefore safe to assume that it's not possible to stream shogi using the old ID as a game?

**Comment by killerducky** [comment]
I tried to stream last week and it didn't pick it up on lishogi. I assume it's because of the ID.

**Comment by killerducky** [comment]
Is there something else needed to get this merged?

**Comment by ddugovic** [comment]
Not that I'm aware of; what do you think @WandererXII ?

**Comment by WandererXII** [comment]
Thanks a lot, sorry about the delay.

**Comment by killerducky** [comment]
@WandererXII Is this live yet? https://www.twitch.tv/shogiexplained is live but it's not showing on lishogi.

**Pull request merged**
