### PR TITLE
Learn section

### PR DESCRIPTION
**Pull request by justremember**

### CODE REVIEW

**Comment by WandererXII** [comment]
Hopefully I didn't complicate things too much for you with this https://github.com/WandererXII/lishogi/issues/267.
All fen values should now be in proper shogi form ('+L' instead of 'U', 'b' goes first, move number instead of turn number, etc.). Colors are now sente/gote instead of white/black.
I didn't test anything in the learn section yet except what the current(live) version uses, so let me know if you run into any bugs, that you didn't see before.
I also fixed the 'intoduction' typo to 'introduction', so you will have to run this `db.learn_progress.update({}, { $rename: {"stages.intoduction": "stages.introduction"}})`

**Comment by justremember** [comment]
That's a nice change, I'm glad this has been done. And thanks for the tips. Will check as soon as I can, hopefully within the next month...

**Comment by justremember** [comment]
Ok just finished rebasing

**Comment by justremember** [comment]
Homestretch... just need to implement dots when selecting pocket piece.

**Comment by justremember** [comment]
This is taking much longer than expected... But I'm done with nearly half of the new levels.

**Comment by justremember** [comment]
@WandererXII how to view the lint errors locally?

**Comment by WandererXII** [comment]
> @WandererXII how to view the lint errors locally?

Oh, sorry I didn't see I was tagged. Just run `npm run lint` and `npm run check-format` (or just `npm run format` to format it)

**Pull request merged**
