### PR TITLE
Variants setup limit

### PR DESCRIPTION
**Pull request by SriMethan**
This pr doesn't allows to create variant rated games less than 30 seconds

### CODE REVIEW

**Comment by TheYoBots** [comment]
1. I suggest you run prettier on your code. 
2. Why though does variant games below 30 secs need to be prevented? It is anyways prevented against AI, why with humans too?

**Comment by SriMethan** [comment]
Have you ever seen lichess allows to create variant rated games less than 30seconds?

**Comment by ch-suginami** [comment]
In my opinion, lishogi could have a variant rated game less than 30 seconds.
lishogi is different from lichess. We would have an option to choose like ultrabullet time control.
In addition to above, one of variant shogi games is the minishogi and the board size is 5x5, which is obviously smaller than normal shogi(9x9). And some players like very short time control(e.g. 1/4 + 1) in normal shogi with rated game.
So there is no reason to prevent less than 30 seconds rated game, rather than players should choose all controlls.

**Comment by SriMethan** [comment]
Maybe I can change this to variant rated games less than 30 seconds without increment and it will allow to create 15 seconds game with increment or byoyomi

**Pull request closed without merging**
