### PR TITLE
Western pieceset

### PR DESCRIPTION
**Pull request by peanatsu**
hi,

I added a western piece set. See https://lishogi.org/forum/lishogi-feedback/i-made-a-western-style-piece-set for reference and screenshots.

Note that there are two commits, the first one was simply updating the piece-css directory, since that was out-of-date. the second commit adds the actual set.

### CODE REVIEW

**Comment by WandererXII** [comment]
Looks great, thanks for making the PR. Sorry I didn't notice sooner on the forum. I expect to update the server over the weekend, so it will probably be live around then.

**Comment by justremember** [comment]
The license is CC BY-SA 3.0. Is it compatible with lishogi's AGPLv3?

**Comment by justremember** [comment]
Ok not README but here: https://github.com/WandererXII/lishogi/blob/master/COPYING.md

**Comment by peanatsu** [comment]
@WandererXII no worries, I'm just happy it gets added.

@justremember good point, I totally forgot about that fille. I would have added the license info in there had I noticed it. Btw, it seems that none of the piece sets of lishogi are currently listed in that file (all the listed sets seem to be lichess sets), so someone may want to hunt down the license info for the various piece sets currently in use.

For mine, the following line can simply be added in the "Exceptions (free)" table:

public/piece/western | [peanatsu](https://github.com/peanatsu) | [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)

Should I make another PR for that?

**Comment by justremember** [comment]
> it seems that none of the piece sets of lishogi are currently listed in that file 
Alright, just made an issue for it.
> Should I make another PR for that?
Yep.

**Pull request merged**
