### PR TITLE
Speech - do not pronounce comma

### PR DESCRIPTION
**Pull request by ddugovic**
Not yet tested.  What I want is that 34 should be read as "three four" rather than "three comma four".

### CODE REVIEW

**Comment by WandererXII** [comment]
For 'P-34' I get "Pawn three four". You want it to say "Pawn three comma four"?

**Comment by ddugovic** [comment]
I should provide more details... in this case I hear "pawn dash seven comma six" instead of "pawn seven six":
URL: https://lishogi.org/analysis#1
Browser/OS: Vivaldi (Windows 10 latest)
image

**Comment by WandererXII** [comment]
I made some improvements, it's live now. Let me know, whether it works how it should. In console you can also see what it's trying to say.

**Comment by ddugovic** [comment]
Thanks, that works for me!

**Pull request closed without merging**
